spring:
  application:
    name: etf-tracker
  datasource:
    url: ${DB_URL:jdbc:postgresql://aws-1-ap-southeast-2.pooler.supabase.com:6543/postgres?prepareThreshold=0&rewriteBatchedInserts=true}
    username: ${DB_USERNAME:postgres.qirtgmojnsuecgzuovjj}
    password: ${DB_PASSWORD:Jwkl13365!@#$%}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 100
        order_inserts: true
        order_updates: true

server:
  port: ${PORT:8080}

app:
  api-key: ${API_KEY:default-dev-secret-key}
  frontend-url: ${FRONTEND_URL:http://localhost:5173}
